version: '3'
services:
  days-abroad-app:
    container_name: days-abroad-app
    image: days-abroad-app
    volumes:
      - /var/lib/telegram-bot:/var/lib/telegram-bot
    ports:
      - "8081:8081"
    restart: always

  nginx-certbot:
    container_name: nginx-certbot
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
            - ./nginx-certbot/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-certbot/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
